version: '3.8'

services:
    postgresDB:
      image: postgres:15.3
      restart: always
      container_name: postgres-db
      environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_DB: ${DB_NAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - 5432:5432
      volumes:
        - ./postgres:/var/lib/postgresql/data